name: Monday
on:
  schedule:
    - cron:  '0 0 * * MON'
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README.md
        run: echo "![Ponedelnik_Mayk_Ermntraunt](https://user-images.githubusercontent.com/62806448/232580077-63c279a2-3f2e-4aa9-bb1c-f2f667e52935.gif)" > README.md
      - uses: EndBug/add-and-commit@v9
        with:
          commiter_email: me@tfk.name
          message: 'Ponedelbnik (⊙ _ ⊙)'
          push: true
