name: Saturday
on:
  schedule:
    - cron:  '0 0 * * SAT'
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README.md
        run: echo "![Subbota_Kayf_Mayk](https://user-images.githubusercontent.com/62806448/232584670-44d222a2-acca-4529-b18e-a3913e6044f4.gif)" > README.md
      - uses: EndBug/add-and-commit@v9
        with:
          commiter_email: me@tfk.name
          message: 'Subbota ( ≖‿  ≖ )'
          push: true
